### ISSUE TITLE
Add versions to dependencies

### ISSUE THREAD

**Issue by tiagojsag** [vizzTools/cookiecutter-data-science#10]
The required python packages are not pinned in any way to specific versions. If one of your dependencies gets a BC break update, you will be exposed to it, and with no easy way to find out which versions used to work.

For each dependency, you should have something like  "~1.1.0" to pin down the minor release version, while still allowing for bugfix  releasese

**Comment by elpamart** [comment]
I've opened a PR which will solve this issue.

**Comment by aagm** [comment]
generated a lockfile from dependencies with fixed versions
